config/routes.rb
Emailtoletter::Application.routes.draw do
  
  devise_for :users, path: "auth", path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'signup' }
  mount Ckeditor::Engine => '/ckeditor'
  
  resources :charges
  resources :orders

  root to: 'orders#new'
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'pricing', to: 'pages#pricing'

end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
  include Ckeditor::Backend::Paperclip
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  has_attached_file :data,
                    :url => "/ckeditor_assets/attachments/:id/:filename",
                    :path => ":rails_root/public/ckeditor_assets/attachments/:id/:filename"

  validates_attachment_presence :data
  validates_attachment_size :data, :less_than => 100.megabytes
  do_not_validate_attachment_file_type :data

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  has_attached_file :data,
                    :url  => "/ckeditor_assets/pictures/:id/:style_:basename.:extension",
                    :path => ":rails_root/public/ckeditor_assets/pictures/:id/:style_:basename.:extension",
                    :styles => { :content => '800>', :thumb => '118x100#' }

  validates_attachment_presence :data
  validates_attachment_size :data, :less_than => 2.megabytes
  validates_attachment_content_type :data, :content_type => /\Aimage/

  def url_content
    url(:content)
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
	
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

  def new
  end

  def create
    # Amount in cents
    @amount = 300

    customer = Stripe::Customer.create(
      :email => 'example@stripe.com',
      :card  => params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      :customer    => customer.id,
      :amount      => @amount,
      :description => 'Rails Stripe customer',
      :currency    => 'usd'
    )

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to charges_path
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

	def new
		@order = Order.new
	end

	def create
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

def home
end

def about
end

def contact
end

end

app/helpers/application_helper.rb
module ApplicationHelper
# Returns the full title on a per-page basis.
	def full_title(page_title)
		base_title = "Email To Letters"
		if page_title.empty?
			base_title
		else
			"#{base_title} | #{page_title}"
		end
	end
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
	
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/states_helper.rb
module StatesHelper

	def us_states
	  [
	    ['Alabama', 'AL'],
	    ['Alaska', 'AK'],
	    ['Arizona', 'AZ'],
	    ['Arkansas', 'AR'],
	    ['California', 'CA'],
	    ['Colorado', 'CO'],
	    ['Connecticut', 'CT'],
	    ['Delaware', 'DE'],
	    ['District of Columbia', 'DC'],
	    ['Florida', 'FL'],
	    ['Georgia', 'GA'],
	    ['Hawaii', 'HI'],
	    ['Idaho', 'ID'],
	    ['Illinois', 'IL'],
	    ['Indiana', 'IN'],
	    ['Iowa', 'IA'],
	    ['Kansas', 'KS'],
	    ['Kentucky', 'KY'],
	    ['Louisiana', 'LA'],
	    ['Maine', 'ME'],
	    ['Maryland', 'MD'],
	    ['Massachusetts', 'MA'],
	    ['Michigan', 'MI'],
	    ['Minnesota', 'MN'],
	    ['Mississippi', 'MS'],
	    ['Missouri', 'MO'],
	    ['Montana', 'MT'],
	    ['Nebraska', 'NE'],
	    ['Nevada', 'NV'],
	    ['New Hampshire', 'NH'],
	    ['New Jersey', 'NJ'],
	    ['New Mexico', 'NM'],
	    ['New York', 'NY'],
	    ['North Carolina', 'NC'],
	    ['North Dakota', 'ND'],
	    ['Ohio', 'OH'],
	    ['Oklahoma', 'OK'],
	    ['Oregon', 'OR'],
	    ['Pennsylvania', 'PA'],
	    ['Puerto Rico', 'PR'],
	    ['Rhode Island', 'RI'],
	    ['South Carolina', 'SC'],
	    ['South Dakota', 'SD'],
	    ['Tennessee', 'TN'],
	    ['Texas', 'TX'],
	    ['Utah', 'UT'],
	    ['Vermont', 'VT'],
	    ['Virginia', 'VA'],
	    ['Washington', 'WA'],
	    ['West Virginia', 'WV'],
	    ['Wisconsin', 'WI'],
	    ['Wyoming', 'WY']
	  ]
	end
end

app/views/charges/create.html.erb
<div align="center">
<h2>Awesome! Your letter will be on it's way!</h2>
</div>

app/views/charges/new.html.erb
<div align="center">
	<%= form_tag charges_path do %>
	  <article>
	    <label class="amount">
	      <span>Amount: $3.00</span>
	    </label>
	  </article>

	  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
	          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
	          data-description="A month's subscription"
	          data-amount="500"></script>
	<% end %>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    &copy <a href="http://emailtoletters.com/">Email To Letters.com</a>
    by <a href="http://cjhudson.com">Chris Hudson</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Email To Letters", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Get Started", root_path %></li>
          <li><%= link_to "About", about_path %></li>
          <li><%= link_to "Pricing", pricing_path %></li>
          <li><%= link_to "Contact", contact_path %></li>
          <% if user_signed_in? %>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                
                <li><%= link_to "Settings", edit_user_registration_path %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", destroy_user_session_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign Up", new_user_registration_path, :class => 'signup-link' %></li>
            <li><%= link_to "Log In", new_user_session_path, :class => 'login-link' %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>
		<%= full_title(yield(:title)) %>
	</title>
	<%= stylesheet_link_tag "application", media: "all",
"data-turbolinks-track" => true %>
	<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	<%= javascript_include_tag 'ckeditor/ckeditor.js' %>
	<%= csrf_meta_tags %>

	<!-- Analytics -->

</head>
<body>
	<%= render 'layouts/header' %>
		<div class="container">
			<% if notice %>
			  <p class="alert alert-success"><%= notice %></p>
			<% end %>
			<% if alert %>
			  <p class="alert alert-danger"><%= alert %></p>
			<% end %>
		<%= yield %>
	<%= render 'layouts/footer' %>
	<%= debug(params) if Rails.env.development? %>
</div>
</body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
<head>
</head>
<body>
  <%= yield %>
</body>
</html>

app/views/orders/_new.html.erb
<%= form_for @order do |f| %>
<h3>To:</h3>
<br>
<p>Name:</p>
<%= f.text_field :to_fname %> <%= f.text_field :to_lname %>
<p>Company:</p>
<%= f.text_field :to_company %>
<p>Address:</p>
<%= f.text_area :to_street %>
<p>Address 2:</p>
<%= f.text_area :to_street2 %>
<p>City:</p>
<%= f.text_field :to_city %>
<p>State:</p>
<%= f.text_field :to_state %>
<p>Zip:</p>
<%= f.text_field :to_zip %>

<h3>From:</h3>

<br>
<p>Name:</p>
<%= f.text_field :from_fname %> <%= f.text_field :from_lname %>
<p>Company:</p>
<%= f.text_field :from_company %>
<p>Address:</p>
<%= f.text_area :from_street %>
<p>Address 2:</p>
<%= f.text_area :from_street2 %>
<p>City:</p>
<%= f.text_field :from_city %>
<p>State:</p>
<%= f.text_field :from_state %>
<p>Zip:</p>
<%= f.text_field :from_zip %>

<% end %>

app/views/orders/create.html.erb
<div align="center">
Flash Success or Errors
-> Data Validations (re-render new)
-> Length of document.

Allow for review of order

Input Stripe Credit Card Charge.
</div>

app/views/orders/new.html.erb
<h1>Email To Letters</h1>

<h2>Send A Letter</h2>

<div>
<br />
<%= form_for @order do |f| %>

<%= f.text_area :content, :class => 'ckeditor' %>
<br />
<h3>To:</h3>
<br>
<p>Name:</p>
<%= f.text_field :to_fname, :placeholder => "First Name" %> <%= f.text_field :to_lname, :placeholder => "Last Name" %>
<p>Company:</p>
<%= f.text_field :to_company %>
<p>Address:</p>
<%= f.text_area :to_street %>
<p>Address 2:</p>
<%= f.text_area :to_street2 %>
<p>City:</p>
<%= f.text_field :to_city %>
<p>State:</p>
<%= f.select :to_state, options_for_select(us_states) %>
<p>Zip:</p>
<%= f.text_field :to_zip, :size=>"10" %>

<h3>From:</h3>

<br>
<p>Name:</p>
<%= f.text_field :from_fname, :placeholder => "First Name" %> <%= f.text_field :from_lname, :placeholder => "Last Name" %>
<p>Company:</p>
<%= f.text_field :from_company %>
<p>Address:</p>
<%= f.text_area :from_street %>
<p>Address 2:</p>
<%= f.text_area :from_street2 %>
<p>City:</p>
<%= f.text_field :from_city %>
<p>State:</p>
<%= f.select :from_state, options_for_select(us_states) %>
<p>Zip:</p>
<%= f.text_field :from_zip, :size=>"10" %>

<div align="center">
<%= f.submit 'Send My Letter!', :class => 'btn btn-primary' %>
</div>

<% end %>
</div>

app/views/pages/about.html.erb
<% provide(:title, 'About') %>
<h1>About Email To Letters</h1>
<p>
Email to Letters was a project built by <a href="http://cjhudson.com">Chris Hudson</a> to understand Rails, Bootstrap, Stripe, and the printing & mailing API from Lob.com.
</p>
<p>
The idea behind Email To Letters came from the want to build something new with the powerful web framework Rails. I want to say thanks to <a href="https://twitter.com/harryzhang">Harry Zhang</a> over @ Lob.com, <a href="https://twitter.com/dhh">DHH</a> the creator of Rails, the whole Stripe team, and <a href="https://twitter.com/mhartl">Michael Hartl</a> @ RailsTutorial.org. I honestly could not have built this without your help and support.
</p>

app/views/pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>

<h2> Do you want to reach out to me? </h2>

<div align="center">
Email me @ chris at cjhudson dot com.

<hr />

Or find me (and this project) @ <a href="http://github.com/TezzellEnt">GitHub.com</a>
</div>

app/views/pages/home.html.erb
<h1>Email To Letters</h1>

<h2>Send A Letter</h2>

<p> Content </p>

app/views/pages/pricing.html.erb
<% provide(:title, 'Pricing') %>
<h1>Email To Letters Pricing</h1>
<div align="center">
<p><strong>Pricing should be fair and cost-effective.</strong></p>
<p>With that in mind, this is the pricing below:</p>
</div>
<br />
<div class="row">
	<div class="col-md-4">
	</div>
	<div class="col-md-4">
	    <div class="panel panel-primary">
	        <div class="panel-heading">
	      	  <h3 class="text-center">Pricing</h3>
	        </div>
	        	 <div class="panel-body text-center">
					<p class="lead" style="font-size:40px"><strong>$2 / Page</strong></p>
				</div>
	      	        <ul class="list-group list-group-flush text-center">
						<li class="list-group-item"><i class="icon-ok text-danger"></i> No Commitment</li>
						<li class="list-group-item"><i class="icon-ok text-danger"></i> Unlimited letters</li>
						<li class="list-group-item"><i class="icon-ok text-danger"></i> My sincere grattitude</li>
					</ul>
	  		<div class="panel-footer">
				<%= link_to 'Get Started!', root_url, class: "btn btn-lg btn-block btn-danger" %> 
			</div>
		</div>
	</div>
	<div class="col-md-4">
	</div>
</div>

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>